### ISSUE TITLE
In order to get the Attention one must write [!DANGER]

### ISSUE THREAD

**Issue by woss** [zanfab/docsify-plugin-flexible-alerts#10]
Instead of 
```
> [!ATTENTION]
> An alert of type 'note' using global style 'callout'.
```
one must write 
```
> [!DANGER]
> An alert of type 'note' using global style 'callout'.
```
I suggest mentioning this in readme file or changing the example

**Comment by zanfab** [comment]
Hi @woss,

can you please provide further details about the location of mentioned example?
I cannot identify one like
> ```
> > [!ATTENTION]
> > An alert of type 'note' using global style 'callout'.
> ```

In general the type you have to use is "DANGER" but title which will be rendered by default is "Attention". This is already mentioned in readme section [Usage](https://github.com/zanfab/docsify-plugin-flexible-alerts#usage).

> To use the plugin just modify an existing blockquote and prepend a line matching pattern [!type]. By default types NOTE, TIP, WARNING and DANGER are supported. You can extend the available types by providing a valid configuration (see below for an example)

Do you might have an idea how this could be described even better?

**Comment by woss** [comment]
Yeah, it's not about the implementation it's about the text that explains it. I wanted to say that you say `attention` when you mean `danger` . 

> By default style 'callout' and headings 'Note', 'Tip', 'Warning', 'Attention' will be used. You can change it using plugin configuration via index.html or for a single alert in your markdown files.

then: 
```js
 danger: { // but here danger. 
        label: {
          '/de-DE/': 'Achtung', // === attention
          '/': 'Attention'
        }
      }
```

I think more semantically would be either `attention` OR `danger` but not both mixed together to mean the same 

p.s.  great job with this plugin. ✋

**Comment by zanfab** [comment]
May you please have a look at PR #13?
I tried to address your issue in a updated readme file.

**Comment by woss** [comment]
i checked and  left the comment :)

**Comment by zanfab** [comment]
> I suggest mentioning this in readme file or changing the example

I have now explicitly pointed out the difference between type and heading.
So from my point of view the readme addresses you issue.
