### ISSUE TITLE
I am not able to use it

### ISSUE THREAD

**Issue by StefanoMartin** [zanfab/docsify-plugin-flexible-alerts#12]
I really like the style of your plugin but I am not able to make it to work.
Maybe you can help me to understand what I am doing wrong.

Here the files.

```html
<!-- index.html -->

<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="UTF-8">
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify/themes/vue.css">
</head>
<body>
  <div id="app"></div>
  <script>
    window.$docsify = {
      'flexible-alerts': {
        style: 'flat'
      }
    };
  </script>
  <script src="//cdn.jsdelivr.net/npm/docsify/lib/docsify.min.js"></script>
  <!-- Latest -->
  <script src="https://unpkg.com/docsify-plugin-flexible-alerts"></script>
</body>
</html>
```

```markdown
<!-- README.md -->
Test
==============

[!NOTE]
An alert of type 'note' using global style 'callout'.
```

**Comment by zanfab** [comment]
Plugin generates alerts based on blockquotes.
So please be aware of the syntax for blockquotes in your markdown as described [here](https://github.com/zanfab/docsify-plugin-flexible-alerts#usage)

In your example markdown should look like following example:

```
<!-- README.md -->
Test
==============

> [!NOTE]
> An alert of type 'note' using global style 'callout'.
```

Please pay attention to the `>` at the start of each line.

Can you please confirm if this does fix your issue?

**Comment by StefanoMartin** [comment]
Oh! This explain a lot. Sorry for my stupid issue and thank you for your answer and your plugin.
