### ISSUE TITLE
Can't get custom font-awesome icons to work

### ISSUE THREAD

**Issue by ndom91** [zanfab/docsify-plugin-flexible-alerts#7]
So I've been trying to use a custom icon, and I cant get it to render at all.

So for example, this is my alert heading where I'm trying to use the [microchip](https://fontawesome.com/icons/microchip?style=solid) icon from fa.
```
> [!NOTE|label:Specs|icon:fas fa-microchip] 
```
I've tried it with `icon:fas-fa-microchip` as well as `icon:fa-microchip` and neither seems to work. I then thought it was maybe this specific Icon, so I tried many other ones from the site as well as the example listed in the README ("fa fa-comments") and nothign worked.

I double checked the source of the `docsify-plugin-flexible-alerts` .js file I'm using, and it does seem to be successfully pulling in the Font Awesome 5.6.3.

Am I missing something about how to use custom Icons, or is there really a bug here?

Thanks guys
Nico

**Comment by KyleFairns** [comment]
I seem to be having this issue too, and have a solution.

The only thing that needs to change is in the Regex that is used to match the setting:

**Original**
`[\s\w\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]`

**Updated**
`[\s\w\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF-]`

In both occurrences of the regex appearing. It'll then match as you'd expect it to.

The issue with the regex is as simple as the assumption that `\w` included hyphens

**Comment by zanfab** [comment]
@ndom91 and @KyleFairns 
Sorry, that it was a bit quiet lately.
There is an issue when icon settings are applied on an alert specific level. If specified in config it does work. I will check the PR and complete it today.

**Comment by zanfab** [comment]
Fixed in release **1.04**
