### ISSUE TITLE
nothing happening after configuring this plugin

### ISSUE THREAD

**Issue by zivl** [zanfab/docsify-plugin-flexible-alerts#9]
I'm doing the step-by-step guide but I cannot see any change.
to reproduce it, please see https://github.com/wix/sentry-testkit/pull/35

**Comment by zanfab** [comment]
Please ensure that you use the correct ordering of script imports as mentioned here: [Docsify Quick Start](https://docsify.js.org/#/quickstart?id=manual-initialization)
So you have to place the script imports of docsify and all plugins after the script `window.$docsify = {}`

Please let me know if this could fix your issue.

**Comment by zivl** [comment]
yep it wasn't `docsify` but something other plugin which it's order conflicting with yours.
Thanks for pointing it out...
